// @build: 2026-06-22 | id: FORM-PERSONAL | desc: Formulario de instructor/proveedor extraído de AdminConfigHub
import { useState, memo, useContext } from 'react';
import { AppContext } from '../../../context/AppContextValue';
import { Button, Input, Select } from '../../../components/UI';
import { ChevronLeft } from 'lucide-react';

const FormPersonal = memo(({ item, onSave, onCancel, rol }) => {
  const { sedes } = useContext(AppContext);
  const isInst = rol === 'instructor';
  const [form, setForm] = useState(item.id ? item : { nombre: '', apellido: '', cedula: '', email: '', password: '', telefono: '', pagoBanco: '', pagoTelefono: '', pagoCedula: '', sedes: [], esPrincipal: false, activo: true });
  return (<div className="space-y-4"><div className="flex gap-2 items-center mb-4"><button type="button" onClick={onCancel} className="p-2 bg-gray-200 rounded-full"><ChevronLeft size={20} /></button><h3 className="font-bold text-lg">{item.id ? 'Editar' : 'Nuevo'} {rol}</h3></div><Input label="Nombre" value={form.nombre} onChange={e => setForm({ ...form, nombre: e.target.value })} />{isInst && <Input label="Apellido" value={form.apellido} onChange={e => setForm({ ...form, apellido: e.target.value })} />}<Input label="Cédula / RIF" value={form.cedula} onChange={e => setForm({ ...form, cedula: e.target.value })} /><Input label="Teléfono" value={form.telefono} onChange={e => setForm({ ...form, telefono: e.target.value })} /><div className="bg-gray-50 p-4 rounded-xl border border-gray-200"><h4 className="text-sm font-bold text-gray-700 mb-2">Acceso Sistema</h4><Input label="Email" type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /><Input label="Contraseña" type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></div><div className="bg-blue-50 p-4 rounded-xl border border-blue-100"><h4 className="text-sm font-bold text-blue-900 mb-2">Datos para recibir pagos</h4><Select label="Banco" options={['Banesco', 'Mercantil', 'Provincial', 'Venezuela', 'Bancamiga', 'BNC', 'Tesoro']} value={form.pagoBanco} onChange={e => setForm({ ...form, pagoBanco: e.target.value })} /><Input label="Teléfono Pago Móvil" value={form.pagoTelefono} onChange={e => setForm({ ...form, pagoTelefono: e.target.value })} /><Input label="Cédula Pago Móvil" value={form.pagoCedula} onChange={e => setForm({ ...form, pagoCedula: e.target.value })} /></div><div className="bg-white p-4 rounded-xl border border-gray-200"><h4 className="text-sm font-bold text-gray-700 mb-3">Sedes Asignadas</h4><div className="flex flex-col gap-2">{(sedes || []).filter(s => s.activo).map(s => <label key={s.id} className="flex items-center gap-3 bg-gray-50 p-3 rounded-lg cursor-pointer"><input type="checkbox" checked={form.sedes?.includes(s.id)} onChange={() => setForm({ ...form, sedes: form.sedes?.includes(s.id) ? form.sedes.filter(id => id !== s.id) : [...(form.sedes || []), s.id] })} className="w-5 h-5 text-blue-600 rounded" /><span className="font-bold text-gray-800">{s.nombre}</span></label>)}</div></div>{isInst && <div className="flex items-center gap-2 p-4 bg-gray-50 border rounded-xl"><input type="checkbox" checked={form.esPrincipal} onChange={e => setForm({ ...form, esPrincipal: e.target.checked })} className="w-5 h-5" /><label className="font-bold text-sm text-gray-700">Definir como Instructor Principal</label></div>}<Button type="button" onClick={() => onSave(form)} variant="dark">Guardar</Button></div>);
});

export default FormPersonal;